apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
stringData:
  DATABASE_PASSWORD: "1234" # Update this value as needed
  JWT_SECRET: s3cr3t # Update this value with your own secret key.
type: Opaque
